# cilium-gateway.yaml
----------
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: default
  namespace: istio-system  # 与 Cilium 同命名空间
spec:
  gatewayClassName: istio  # 指定使用 Cilium GatewayClass
  listeners:
  - name: http  # 监听名称
    protocol: HTTP  # 协议
    port: 80  # Envoy 监听的端口（内部端口，外部通过节点端口暴露）
    allowedRoutes:
      namespaces:
        from: All  # 允许路由来自所有命名空间的服务

---------

apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: https
  namespace: istio-system
spec:
  gatewayClassName: istio
  listeners:
  - name: https
    port: 443
    protocol: HTTPS
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        name: bei-tls  # 证书仍限制域名，仅关联证书
        namespace: istio-system
    allowedRoutes:
      namespaces:
        from: All  # 允许所有命名空间的路由关联到此网关