apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
  namespace: argocd
spec:
  project: tools
  source:
    repoURL: git@github.com:bsonger/tools.git
    targetRevision: main
    path: ./argo-rollouts
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-rollout
  syncPolicy:
    automated:
      prune: true          # 自动删除未在 Git 中定义的资源
      selfHeal: true       # 如果资源被修改，自动纠正
    syncOptions:
      - CreateNamespace=true