apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: jupyter-web-app
spec:
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/istio-system/sa/istio-ingress
              - cluster.local/ns/kubeflow/sa/oauth2-proxy-kubeflow
  selector:
    matchLabels:
      app: jupyter-web-app
