apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: jupyter-web-app-jupyter-web-app
spec:
  gateways:
  - kubeflow-gateway
  hosts:
  - '*'
  http:
#  - headers:
#      request:
#        add:
#          x-forwarded-prefix: /jupyter
#    match:
#    - uri:
#        prefix: /jupyter/
#    rewrite:
#      uri: /
#    route:
#    - destination:
#        host: jupyter-web-app-service.$(JWA_NAMESPACE).svc.$(JWA_CLUSTER_DOMAIN)
#        port:
#          number: 80
  - match:
    - uri:
        prefix: /jupyter/oauth2/callback
    route:
    - destination:
        host: oauth2-proxy.oauth2-proxy.svc.cluster.local  # oauth2-proxy 服务地址
        port:
          number: 80
  # 规则2：其他 /jupyter/ 路径的请求，先转发到 oauth2-proxy 认证
  - match:
    - uri:
        prefix: /jupyter/
    rewrite:
      uri: /
    route:
    - destination:
        host: oauth2-proxy.oauth2-proxy.svc.cluster.local
        port:
          number: 80
    headers:
      request:
        add:
          x-forwarded-prefix: /jupyter  # 保留 Jupyter 所需前缀