apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: trace-demo
  namespace: open-telemetry
spec:
  mode: deployment
  replicas: 1
  image:  otel/opentelemetry-collector-k8s:0.126.0
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
      batch:
        timeout: 10s
        send_batch_size: 512

    exporters:
      debug: {}
      otlp:
        endpoint: "tempo.monitoring.svc.cluster.local:4317"  # Tempo ClusterIP + OTLP gRPC


    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [otlp]