apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: trace
  namespace: observability
spec:
  mode: deployment
  replicas: 1
  image: otel/opentelemetry-collector-contrib:0.143.0

  ports:
    - name: otlp-grpc
      port: 4317
    - name: otlp-http
      port: 4318
    - name: metrics
      port: 8889

  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      zipkin:
        endpoint: 0.0.0.0:9411
      nop: {}

    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15


      # ---------- METRICS ----------
      metricstransform:
        transforms:
          - include: traces.span.metrics.calls
            action: update
            new_name: http_requests_total
          - include: traces.span.metrics.duration
            action: update
            new_name: http_request_duration

      batch:
        timeout: 10s
        send_batch_size: 512

    connectors:
      spanmetrics:
        histogram:
          explicit:
            buckets: [100us, 1ms, 2ms, 6ms, 10ms, 100ms, 250ms]
          dimensions:
            - name: http.request.method
            - name: http.response.status_code
            - name: http.route

        calls_dimensions:
          - name: http.request.method
          - name: http.response.status_code
          - name: http.route

        exemplars:
          enabled: true
          max_per_data_point: 1

        aggregation_temporality: CUMULATIVE

        resource_metrics_key_attributes:
          - service.name
          - service.namespace

    exporters:
      # ---- traces ----
      otlp:
        endpoint: tempo-distributor.monitoring.svc.cluster.local:4317
        tls:
          insecure: true

      # ---- metrics ----
      prometheus:
        endpoint: 0.0.0.0:8889
        enable_open_metrics: true
        resource_to_telemetry_conversion:
          enabled: true

      debug:
        verbosity: detailed

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [spanmetrics, otlp]

        metrics:
          receivers: [spanmetrics]
          processors: [batch, metricstransform]
          exporters: [prometheus]
