apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: ci
  namespace: tekton-pipelines
spec:
  params:
    - {name: git-url,        type: string}
    - {name: git-revision,   type: string,  default: main}
    - {name: image-registry, type: string}
    - {name: image-name,     type: string}
    - {name: image-tag,      type: string,  default: latest}
    - {name: DOCKERFILE,      type: string,  default: Dockerfile}
  workspaces:
    - {name: source}
    - {name: dockerconfig}
  tasks:
    - name: clone
      taskRef: {name: git-clone}
      params:
        - {name: url,      value: $(params.git-url)}
        - {name: revision, value: $(params.git-revision)}
      workspaces:
        - {name: output, workspace: source}

    - name: build-and-push
      runAfter: [clone]
      taskRef: {name: kaniko-build-push}
      params:
        - name: IMAGE
          value: $(params.image-registry)/$(params.image-name):$(params.image-tag)
        - name: DOCKERFILE
          value: $(params.DOCKERFILE)
      workspaces:
        - {name: source,       workspace: source}
        - {name: dockerconfig, workspace: dockerconfig}