apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: app
  namespace: argo-cd
spec:
  description: "监控相关应用，如 Prometheus / Grafana / Loki"

  # 允许同步的 Git 仓库
  sourceRepos:
    - "https://github.com/bsonger/manifests.git"

  # 允许部署的集群和命名空间
  destinations:
    - namespace: app
      server: https://kubernetes.default.svc
  # 允许操作所有集群级资源
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"

  # 不限制命名空间资源
  namespaceResourceBlacklist: []

  # Roles（可选，如果不创建则默认权限由 Argo CD RBAC 决定）
  roles: []