apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oauth2-proxy
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: git@github.com:bsonger/devops-config.git
    targetRevision: main
    path: ./oauth2-proxy/helm/oauth2-proxy
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: oauth2-proxy
  syncPolicy:
    automated:
      prune: true          # 自动删除未在 Git 中定义的资源
      selfHeal: true       # 如果资源被修改，自动纠正
    syncOptions:
      - CreateNamespace=true