apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-base
  namespace: argocd
spec:
  project: infra
  source:
    repoURL: git@github.com:bsonger/infra.git
    targetRevision: main
    path: ./istio-base
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true          # 自动删除未在 Git 中定义的资源
      selfHeal: true       # 如果资源被修改，自动纠正
    syncOptions:
      - CreateNamespace=true